env:
  app:
    secrets:
      tokenKey:
        ? name
        ? arn
  debug: "false"
  domain:
    sub:
      device:
        appid: null
        apikey: null
        path: /prod
      website:
        ? name
  region:
    ? primary
    ? regions
  sms:
    origin: ""
  stacks:
    core: mytaptrack-null
  student:
    remove:
      timeout: .nan
  regional:
    replication: "false"
    templates:
      ? path
