"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MttEventType = void 0;
var MttEventType;
(function (MttEventType) {
    MttEventType["user"] = "user-config";
    MttEventType["team"] = "team";
    MttEventType["da"] = "dashboard";
    MttEventType["ns"] = "notification-summary";
    MttEventType["student"] = "student-config";
    MttEventType["b"] = "behavior";
    MttEventType["a"] = "app";
    MttEventType["nu"] = "notification-user-config";
    MttEventType["na"] = "notification-app-config";
    MttEventType["ds"] = "device-student-config";
    MttEventType["d"] = "device-config";
    MttEventType["ad"] = "app-device-config";
    MttEventType["as"] = "app-student-config";
    MttEventType["dn"] = "notification-dashboard";
    MttEventType["i"] = "team-invite";
    MttEventType["ne"] = "note-event";
    MttEventType["trackEvent"] = "track-event";
    MttEventType["trackService"] = "track-service";
    MttEventType["trackLowPower"] = "track-low-power";
    MttEventType["behaviorChange"] = "behavior-change";
    MttEventType["requestNotify"] = "request-notify";
    MttEventType["license"] = "license";
    MttEventType["reportProcessEvent"] = "report-process-event";
})(MttEventType || (exports.MttEventType = MttEventType = {}));
//# sourceMappingURL=eventbus.js.map